import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/gfhghg/header";
import { Footer } from "@/gfhghg/footer";

export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
